-- Create todos table
create table public.todos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users,
  task text,
  is_complete boolean,
  inserted_at timestamp with time zone default (now() AT TIME ZONE 'utc'::text) not null
);

-- Enable RLS
alter table public.todos enable row level security;

-- RLS Policy: INSERT - Individuals can create todos
create policy "Individuals can create todos."
  on public.todos
  for insert
  to public
  with check (
    (auth.uid() = user_id)
  );

-- RLS Policy: SELECT - Individuals can view their own todos
create policy "Individuals can view their own todos."
  on public.todos
  for select
  to public
  using (
    ((SELECT auth.uid() AS uid) = user_id)
  );

-- RLS Policy: UPDATE - Individuals can update their own todos
create policy "Individuals can update their own todos."
  on public.todos
  for update
  to public
  using (
    ((SELECT auth.uid() AS uid) = user_id)
  );

-- RLS Policy: DELETE - Individuals can delete their own todos
create policy "Individuals can delete their own todos."
  on public.todos
  for delete
  to public
  using (
    ((SELECT auth.uid() AS uid) = user_id)
  );
